### ISSUE TITLE
Exceptions by using primitive values in EntryToModelConverter

### ISSUE THREAD

**Issue by dbeuchler** [PHOENIXCONTACT/MORYX-Platform#35]
**Describe the bug**
There is a bug with primitive values while using the `EntryToModelCoverter`. No prototypes can be created and also the tests are failing

**To Reproduce**
1. Run tests: `EntryToModelConverterTests`

**Comment by Toxantron** [comment]
I turned out it was not a problem with primitives, but actually with faulty dictionary detection. As a result a `Dictionary<int, SomeClass>` was prototyped as integer with class `SubEntries`.

**Comment by Toxantron** [comment]
I isolated the issue within `EncodeObject` of the result object, more general a collection. We currently only support primitives or single objects, but not collections.
