### ISSUE TITLE
EntryConvert: Problem for arrays of primitives

### ISSUE THREAD

**Issue by dbeuchler** [PHOENIXCONTACT/MORYX-Platform#38]
The test function

```C#
[EditorBrowsable, Description("Returns the string that was sent.")]
public string[] Echo3(string message)
{
  return new [] { "t1", "t2", "t3"};
}
```

gave me a `StackOverflowException`:

![image](https://user-images.githubusercontent.com/26304706/91485458-2f5e9200-e8ab-11ea-9bfb-20fbc2fac10c.png)

_Originally posted by @mmarkwort in https://github.com/PHOENIXCONTACT/MORYX-MaintenanceWeb/pull/17#discussion_r478642415_

**Comment by Toxantron** [comment]
Let me start this issue by saying strings and especially collections of them have been such a pain for ages in `EntryConvert`.

**Comment by Toxantron** [comment]
I isolated the issue, without suprise, within EncodeObject of the result object, more general a collection. We currently only support primitives or single objects, but not collections.
