### ISSUE TITLE
Supporting CORS in WebHttp

### ISSUE THREAD

**Issue by mmarkwort** [PHOENIXCONTACT/MORYX-Platform#49]
Currently the WebHttp host configuration does not support cors. So, requests from clients of other locations than server:port will be blocked.

**Comment by Toxantron** [comment]
I might be wrong, but CORS is only relevant on the client, meaning it will reject responses without the header if script origin and call target don't match. I didn't have any problems and neither does the MaintenanceWeb, so could you elaborate where you had issues? I am not against the change, simply curious what happend.

**Comment by mmarkwort** [comment]
I had some issues with this yesterday. Test it please with swagger or Postman. https://en.wikipedia.org/wiki/Cross-origin_resource_sharing

**Comment by Toxantron** [comment]
Is it possible you were using the Swagger or Postman WebClient? That would explain your CORS issues.

But in case someone else wants to integrate our endpoints in their application, they would run into the same issue.

**Comment by mmarkwort** [comment]
Yes, I write also an openapi.json for the products part and using a swagger tool within VS Code to test it.

**Comment by Toxantron** [comment]
Closed by #50.
