### ISSUE TITLE
Weired behavior in Entry protoypes

### ISSUE THREAD

**Issue by dbeuchler** [PHOENIXCONTACT/MORYX-Platform#75]
If I add a `string` entry to a list of strings a dropdown will be provided. This happens because the prototype of the collection contains `PossibleValues`:

````cs
// From EntryEditor
dataTemplate = configEntryModel.PossibleValues == null ? StringTemplate : DropDownTemplate;
````

![image](https://user-images.githubusercontent.com/920832/98271343-26b3c780-1f90-11eb-8c3e-bd74b243fc36.png)

The same happens for `long`, `int`, `short`. For `char` no prototype can be created (`Type` will be classified as `string`)

For enums it is a bit more confusing. Within the list of possible values are no enum members.

![image](https://user-images.githubusercontent.com/920832/98272193-1bad6700-1f91-11eb-9662-23a9483d9ffc.png)

This will be also cause problems if https://github.com/PHOENIXCONTACT/MORYX-MaintenanceWeb/issues/25 will be done.

**Comment by Toxantron** [comment]
I am pretty sure this IS the cause for PHOENIXCONTACT/MORYX-MaintenanceWeb#25. I'll take a look at it, something went wrong with prototypes for primitives.
