### ISSUE TITLE
EntryConvert: ReadOnly property can be edited

### ISSUE THREAD

**Issue by dbeuchler** [PHOENIXCONTACT/MORYX-Platform#85]
**Describe the bug**
I am having a property within an Resource and this propery should be readable only (in ui, entryconvert).

````cs
[EntrySerialize]
public StateClassification RemoteDriverState { get; private set; }
````

The UI provides me an editable combo box for this property.

**Comment by Toxantron** [comment]
Because it is technically not read-only. It does have a *Setter*, private or not does not turn it into a readonly property in the reflection API. You can decorate with `[ReadOnly(true)]` or remove the setter.
